#!/bin/sh
if test z$1 = z
then
	echo "usage: jrt-clone-repo URL"
	exit 1
fi
test -d pkg || mkdir pkg
echo "cloning: repopkgs"
wget -O repopkgs $1/repopkgs 2> /dev/null
for i in $(cut -f 1 repopkgs)
do
	echo "cloning: $i.jpkg"
	wget -O $i.jpkg $1/$i.jpkg 2> /dev/null
	cd pkg
	echo "creating: pkg/$i"
	tar xzf ../$i.jpkg 
	cd ..
done
